# fly -t concourse1 configure -c pipeline.yml --vars-from credentials.yml test-buildpacks
---
groups:
  - name: stage
    jobs:
      - test-buildpack-stage

  # - name: prod
  #   jobs:
  #     - test-buildpack-prod

  - name: ci-image
    jobs:
      - build-task-image      
jobs:
  - name: build-task-image
    public: true
    serial: true
    plan:
    - get: pipeline
      resource: git-pipeline-docker-image
      trigger: true
    - get: cf-cli
      trigger: true
    - task: combined
      config:
        platform: linux
        image: docker:///busybox
        inputs:
        - {name: pipeline, path: .}
        - {name: cf-cli, path: ci/ci_image/cf-cli}
        run: {path: echo}
    - put: docker-image
      params:
        build: combined/ci/ci_image

  - name: test-buildpack-stage
    plan:
      - get: time-cron
        trigger: true

      - get: git-buildpacks-test
        trigger: false

      - task: make-manifest
        config:
          platform: linux
          image: {{docker-hub-task-image}}
          inputs:
            - {name: git-buildpacks-test, path: .}
          run:
            path: make-manifest.sh
            # args: [ stage ]

      # - try:
      - put: cf-stage-nodejs
        resource: cf-stage
        params: { manifest: make-manifest/nodejs/manifest-stage.yml }
        on_failure:
          put: vo-alert
          params:
            type: CRITICAL
            entity: "concourse/jobs/test-buildpack-stage/cf-stage-nodejs"
            message: "build failed"

      # - try:
      #   - put: cf-stage-php
      #     resourse: cf-stage
      #     params: { manifest: make-manifest/php/manifest.yml }
      #     ...

resources:
  - name: docker-image
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-create-hub-task-image}}

  - name: cf-cli
    type: s3
    source:
      bucket: go-cli
      regexp: releases/v(.*)/cf-linux-amd64.tgz

  - name: vo-alert
    type: victorops-notification
    source:
      url: {{victorops-url}}


  - name: git-pipeline-docker-image
    type: git
    source:
      uri: {{pipeline-git-repo}}
      branch: {{pipeline-branch}}
      paths: [ci/ci_image/*]

  - name: git-buildpacks-test
    type: git
    source:
      uri: {{pipeline-git-repo}}

  - name: time-cron
    type: time
    source:
      interval: 10m

  - name: cf-stage
    type: cf
    source:
      api: {{cf-stage-api}}
      username: {{cf-stage-username}}
      password: {{cf-stage-password}}
      organization: {{cf-stage-organization}}
      space: {{cf-stage-space}}
      skip_cert_check: false

  - name: cf-prod
    type: cf
    source:
      api: {{cf-prod-api}}
      username: {{cf-prod-username}}
      password: {{cf-prod-password}}
      organization: {{cf-prod-organization}}
      space: {{cf-prod-space}}
      skip_cert_check: false

