jobs:
- (( merge ))
- name: test-nodejs-buildpack-prod
  plan:
    - get: time-cron
      trigger: true

    - get: git-buildpacks-test
      trigger: false

    - task: make-manifest
      config:
        platform: linux
        image: {{docker-hub-task-image}}
        inputs:
          - {name: git-buildpacks-test, path: .}
        run:
          path: ./make-manifest.sh
          args: [ nodejs, prod ]

    - put: cf-prod-nodejs
      resource: cf-prod
      params: { manifest: make-manifest/buildpacks/nodejs/manifest-prod.yml }
      on_success:
        put: vo-alert
        params:
          type: OK
          entity: "concourse/jobs/test-nodejs-buildpack-prod/cf-prod-nodejs"
          message: {{victorops-nodejs-success-prod}}
      on_failure:
        put: vo-alert
        params:
          type: CRITICAL
          entity: "concourse/jobs/test-nodejs-buildpack-prod/cf-prod-nodejs"
          message: {{victorops-nodejs-failure-prod}}
