jobs:
- (( merge ))
- name: test-ruby-buildpack-stage
  plan:
    - get: time-cron
      trigger: true

    - get: git-buildpacks-test
      trigger: false

    - task: make-manifest
      config:
        platform: linux
        image: {{docker-hub-task-image}}
        inputs:
          - {name: git-buildpacks-test, path: .}
        run:
          path: ./make-manifest.sh
          args: [ ruby, stage ]

    - put: cf-stage-ruby
      resource: cf-stage
      params: { manifest: make-manifest/buildpacks/ruby/manifest-stage.yml }
      on_success:
        put: vo-alert
        params:
          type: OK
          entity: "concourse/jobs/test-ruby-buildpack-stage/cf-stage-ruby"
          message: {{victorops-ruby-success-stage}}
      on_failure:
        put: vo-alert
        params:
          type: CRITICAL
          entity: "concourse/jobs/test-ruby-buildpack-stage/cf-stage-ruby"
          message: {{victorops-ruby-failure-stage}}
