jobs:
- (( merge ))
- name: test-staticfile-buildpack-stage
  plan:
    - get: time-cron
      trigger: true

    - get: git-buildpacks-test
      trigger: false

    - task: make-manifest
      config:
        platform: linux
        image: {{docker-hub-task-image}}
        inputs:
          - {name: git-buildpacks-test, path: .}
        run:
          path: ./make-manifest.sh
          args: [ staticfile, stage ]

    - put: cf-stage-staticfile
      resource: cf-stage
      params: { manifest: make-manifest/buildpacks/staticfile/manifest-stage.yml }
      on_success:
        put: vo-alert
        params:
          type: OK
          entity: "concourse/jobs/test-staticfile-buildpack-stage/cf-stage-staticfile"
          message: {{victorops-staticfile-success-stage}}
      on_failure:
        put: vo-alert
        params:
          type: CRITICAL
          entity: "concourse/jobs/test-staticfile-buildpack-stage/cf-stage-staticfile"
          message: {{victorops-staticfile-failure-stage}}
